Repository sequentech/iam, pull requests merged in 2023-09, with the labels that each got.

#303 Security updates
  requirements.txt
Labels: dependencies

#304 Security updates (#303)
  requirements.txt
Labels: dependencies

#305 ✨ Multilingualism (#295)
  iam/api/models.py
  iam/authmethods/m_dnie.py
  iam/authmethods/m_email.py
  iam/authmethods/m_email_otp.py
  iam/authmethods/m_emailpwd.py
  iam/authmethods/m_openidconnect.py
  iam/authmethods/m_pwd.py
  iam/authmethods/m_smart_link.py
  iam/authmethods/m_sms.py
  iam/authmethods/m_sms_otp.py
  iam/utils.py
Labels: enhancement

#306 ✨ Role-based login for election manager
  iam/api/views.py
Labels: enhancement, breaking-change

#297 Automated start/stop support
  iam/api/middleware.py
  iam/api/migrations/0052_authapi_scheduled_events.py
  iam/api/models.py
  iam/api/tasks.py
  iam/api/tests.py
  iam/api/urls.py
  iam/api/views.py
  iam/iam/settings.py
  iam/iam/test_settings.py
  requirements.txt
Labels: enhancement

#308 🐞 Resend auth codes in email-otl or sms-otp doesn't work in alt-auth-method (#307)
  iam/api/tests.py
  iam/api/views.py
Labels: bug

#310 Fix unit tests
  iam/api/tests.py
Labels: bug

#309 Fix unit tests
  iam/api/tests.py
Labels: bug

#311 🐞 Login allowed with election closed
  iam/api/tests.py
  iam/api/views.py
Labels: bug

#312 🐞 Login allowed with election closed (#311)
  iam/api/tests.py
  iam/api/views.py
Labels: bug

#313 Fix send_codes for alt auth methods
  iam/authmethods/m_email_otp.py
  iam/authmethods/m_sms_otp.py
  iam/authmethods/utils.py
  iam/utils.py
Labels: bug
