Repository sequentech/iam, pull requests merged in 2024-04, with the labels that each got.

#334 ✨ Election turnout overview / graph for election managers
  iam/api/models.py
  iam/api/urls.py
  iam/api/views.py
Labels: enhancement

#335 ✨ Check if the authorities are online
  iam/api/tasks.py
Labels: enhancement

#336 ✨ Election turnout overview / graph for election managers (#334)
  iam/api/models.py
  iam/api/urls.py
  iam/api/views.py
Labels: enhancement

#337 ✨ Check if the authorities are online (#335)
  iam/api/tasks.py
Labels: enhancement

#338 🐞 OIDC: Use Authorization Code Flow instead of implicit flow
  iam/authmethods/m_openidconnect.py
  requirements.txt
Labels: bug

#339 🐞 OIDC: Use Authorization Code Flow instead of implicit flow
  iam/authmethods/m_openidconnect.py
Labels: bug

#332 🐞 Trustees struggle to respond to director
  iam/api/tasks.py
Labels: bug

#340 🐞 OIDC: Use Authorization Code Flow instead of implicit flow
  iam/authmethods/m_openidconnect.py
  requirements.txt
Labels: bug

#341 🐞 Trustees struggle to respond to director (#332)
  iam/api/tasks.py
Labels: bug

#342 🛡 Security updates
  requirements.txt
Labels: dependencies

#343 🛡 Security updates (#342)
  requirements.txt
Labels: dependencies

#344 ✨ Download election turnout
  iam/api/views.py
Labels: bug
